---
- project:
    vars:
      ensure_tox_version: '<4'
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-vault-tox-py39
        - k8sapp-vault-tox-pylint
        - k8sapp-vault-tox-flake8
        - k8sapp-vault-tox-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-vault-tox-py39
        - k8sapp-vault-tox-pylint
        - k8sapp-vault-tox-flake8
        - k8sapp-vault-tox-metadata
    post:
      jobs:
        - stx-vault-armada-app-upload-git-mirror

- job:
    name: k8sapp-vault-tox-py39
    parent: openstack-tox-py39
    description: |
        Run py39 for vault armada app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-vault/*
    vars:
        tox_extra_args: -c python3-k8sapp-vault/k8sapp_vault/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-vault-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp_vault
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-vault/k8sapp_vault/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-vault-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_vault
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-vault/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-vault/k8sapp_vault/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-vault-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp_vault
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-vault/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-vault/k8sapp_vault/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-vault-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/vault-armada-app to
      github.com/starlingx/vault-armada-app
    vars:
      git_mirror_repository: starlingx/vault-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-vault-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-vault-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - EM3yUeLr7B2ZfGC4fk+Cycddp2q61VsDEVyTl6g6M4i2hP7j+9u/m907XglmW0EdvRchz
          xSjbMdT0bWsJOSFMLR2qbqKTFYv/eJdSXOGHfv7xQMAiUryyJUm6qXZCpKik9C8jEVKD3
          YLDZ2tZaabNVOznkdpU/GRHYlAo0mvhQwQgvx1rUaRzdw17joGv/+4x9epaf4O+0jcY8g
          OsQ2VWLyA4O9FdEWFmodqmIxDQEqMg7ttBeK3SK0A8SDjAHNcZHNdEIAMHNHP8gb0YTu9
          jXNPRXqdCpOGWSZX/P5mnLCbjTse0dmj59nRi/nvyjPcwFMRAvbC+4zMXdGK4KOr3KOVk
          fh3Hqk1TK6Fd72sv7BTTyEx1hTkCxCecTmqh4FBkOFiG6YmeekRBrSPlOsAg4SgCPvfF9
          nfncvE1JumqYNzoz8A0y4LfeGQvh6u42xBdR+sF5EoqRf+w0pPnGx4ehm5ETUYHfHsp3v
          7cMjcAzs6kl34N/aLbWvC5vwkxtAuQU73ETxNaQsMqh2YyhtObUFlyd5mhgL7XY00ejs4
          lisfOcYlMv4/P6QIUNNaL1R7mgjjhfGAAH0h5xqTH9pIYJOAzaMGif4pj3BYHuCseQEkh
          u9jKTd/JrZZpYZfegUkiBTCGlQJxu7Gff9aBZq+XA2/lkjX3CikmeGJVvL+ECA=
        - S+OglJyGucdHnKxPUxho5UdoXL2TiN1SgiKv1WV8SiRxaAUAhy+DA0s0V+ccchumHkVIh
          iYqF9EIBQEOwPmzHJoxKKyvb/O4n9pk5CS28tuFCytGnq81oLVyBrwhzs2Wcf/jJ0/AAr
          7c7PtIyUpCpgoKM38Vk/fX5vTVWpDznuN7uDvC2IfLN9/HaoOsGpyMxfbiJ7ETabF7GvL
          vZNNmSoDuhL3sMKICO/MH8ENqoFGehLPWPsHGLgYsUFwzNvB9KXHBtLs1xBdCMmzWWcGt
          M9UFidopVx+FFrVtd0Hz4VSiu7oCcU5u+i/R98b3wDOEHqUmfd1Fj/zdo6LoEpOmDWImp
          McM88VkZRIzr+9Qv5esCYSlahHFNHqL4ymSVgv5R2XGO5xVTYMJ3gTJQMYgnLAqBwo8yk
          JzBEhD1QvLIH0yeqKK31oIraSD0geBrh9WmMKykdbWR9qhEIzC0vUtGYalKr/m0PEe8I+
          7xdyQy9A8WPBRRnq3nvfJ+xMpggTsZj7uH41rTi9Z0rlKahKtK1Dx/lWyE56sxC+Ehphv
          PLbIDd0gwXBx4MVwDs7A2kW1VKH9/F6Uz3a7Ld1in4VhPJTfnEm7t5MrzAGvENjRAeljO
          5Mq8W8NK9+8McLuCjBN8hcPBpNrF/0a9tCW/AkUQn8/XByTSdniTn3ej3VfWPc=
        - smBRpl5O+fj4VWkWk0zWJQ5btLGiXhSCA+hb7HYouN4rcm0BztXg6zTSfSkwQDFV6Nzdy
          1IXDnaTbd9TelgdlRwcp2Fm4/BY8oZPPzRkgRL1RbNI+E8x6zOaDrg04g8gas+oho7AXB
          kwxdMC8FyBHmgpkJ2nGxxE23I0ek4RGCjN9s5OClQ3IURt3JHjsj87WFOkchxORYBcfrH
          A7f1uiLLpgaKnNghh0j+q/VEE0pRylCO571FwdqGTn3m6Qorw9gYWVOxbuaN28ZIaYbUT
          ZLPmezE+w4ac1zqU6TVX2vRD2JR66Shq9W7uwwAoFermDz1qdceglAaY1xUq5fT5cmEko
          rjREEPRLFNz9vOvBPKYRmViq3tzu0T3eZUARwuQOY9EJ00wYfIe1D+YRQOajBm30y+5uy
          +3L0bJX+geKN+iVki6RkfpEWofcE12H2BSSTjmxXu5KVS+JYCxom4jRDi+TTjBUNTX5sS
          tEjyLciU1u3v39k3a7oFFoxhxD3hJuLr7r4WVz+DTxUAEsCJzU6EMcqPTxj53ORU2Bh+0
          0ozsBSbgAvTZEZ7otKAqSANwnBvJ+Kj1Kq4OaGG5julHMoQauNA+F4XuRSWLWz9Razgf9
          fruRPg6cSA8WSUgozOAM83zzz29CswkY9jaePfLZqUj0vGR1TRfOs2w2yhxMx8=
        - CUDyWtuYYMfoqHb7gGC6rYNoYELuFMS7Tpm/8seRdWUgFbNRhStSn0rBMtR3CRTao6Rtf
          zBAmPAAujjANpjZhA7aZxPp4bO62Z14ggdSDrNGFfQIxi+QXqlB6otIkmBw8YWrinQksr
          PIFsvmVNKzxzd49GSy/GNxpAnsS2UsVqDo+yUldcRFczRyX75SZhjF2wKm2FPcuXK75Ep
          jqyr8uVRrKV9jTrrbdBqbVYO9r9pAW0g6bLTeEGP9dGxXwwBtrqpxzcX+CO86YorrTJSN
          KkvfH+ftK/0RHpFHuDmwO3BugGQazYUhFkYQEQmaGDoT/LWMdEMjk3JPygHUP9o4N0cSd
          KNNX2uFMkfKAHrhna5qdeONpK8wBMPVcwf/gCNicagNVuXL647xiuuTQP3PZm2dctrO4j
          573toYNbS8r4IqnvO4pDhNR44kYoxFcoAJpOJ1WVIwn+DWd2ATgGkaEQ2L4yzZn68ztPT
          BQ2004/C+8ofND5hXIL2P4RRhzvsS47vLZJt1NCupf7TxJsItDF+ZegqlJyQ55j0ULG2s
          1NbHMgAwSGsQjS501AXPHtgvthfmx4c7KyT6cYpy5o8CbkAe9yAD4wipbPDostjJXTrpz
          Be5Xm5kmswnFWrCIHkIKUpKRlNhMYCLnTX276tkNQ7zBx1AlWZlZyVB6eJLrIE=
        - n6KPO4/fvA2KBTrjja8lXM8/02DSS+cKpXl13XIH5Offl3SStqkJLHCSD8DZmkZ/CQvxG
          //zA/JM/x35oiz4ZOoh48KPJJbriYQe92IHRZ87qhNX3gRP2iwTKL8MTnJ7Vechd3aX98
          T8vdV74nhHB3JMSIX/2ybD33ekjMHK6CZjxbs49d5PwwwxmHCbA+z3APtipBJ0+yaYx7z
          i+0oBZl1kmOXLuWz/svJOfckwIbtNZ+H+jxjXEInt5Hs6X7I7WqMZTniNZidfbYZT/aEx
          I6UEQY6gl1KBS2XWBxxUAqFUUPjLL2+cY4mK2VOf8AG5KdQpKWX7nApjVbi2tdjeyyjvv
          swevAlYmeQ9rTeL8cF+OwuJP2hh+MRt+jl8Cct5FXPFeUsmgWOeUTm1ixZYzQoNa75GqF
          NKaKy/wW5rhbHIrg34KWNGwISBRuYvfGHAafWxuhGvZfqj3LM0hBnGefL8/47MoVyg3mH
          2nS9yID2ru0fTcAg5yxB7r5D6w84oMJJmMmlGGn+QDgnGgz0qdRV/PBtJHGnioPg0PSF9
          PhVErPnU0RLetYpAh+URIRzNQn88ygTe1pMCR+CjRdykbj45Jm0PZihduv47bvDMg69Be
          NgqkA8qnGdfXEcQCkK2CCEAChfMsuGx0X9pul8fYfwQuPc1hvM9uuRmJMGq9SI=
        - Cck5oYJi6Lja4k3rU1TWDJJj1IrhMZX2ozat1m3pRJEwbEiz4X4FBYvZw1nSd3kVJus+l
          paY0uJ5KNMKC5kRiZ2yhVXBQCFrOMaqG1QmTqvH/Z4orCCNV7eA1puJiBGt/siSLr5+Uo
          JbTjO8cVVRUjx/w2Wbr80bQhyQlWXWbO4dy4pr75tr3KlIoTLkKrlSIC7Q45lPVAxFBab
          4O+GQiv/IxdBD3J007KUGdh94B33FVa9xfwE6itGY92eLqvYINOPTxi5hgZuTWpUVsaGn
          qTrpb6NbtAm+2sgrMuPg6a+v6sDcMN5cltsVu9sLCyMisr7ArsRU7jRbLIqWRx8LZnu/c
          xfpFsO+cu47smI7yiE6jNTS2R6Skyze/pDFbb6tNTilk5xm8r798Fg1FOupJwkywI6FRS
          TmK610iNNFfgG/rnTkyuZNGxHs5h0uXDkiZ+FB5wnrw6Jh2J7QuIJMqe1JQQv6bu+oLL3
          fpIAdpNXQ32IcS6w6bvx+bZn37EW0sp2d1TWlIDle1mrD4q3ZkgCo1fRynZA9MM2hOT6I
          XC0gkbEVWzyRgBv8t6UO/qp2j2HIy4wQmvnMEciojDO+EMG65ld0nOaFgdxkSGJKd08hr
          7BWElEugnD9zg/i7jt+pF1dvFpd1JU0nOjTP02H5TCwdenSKrA0jHC+PmslpD8=
        - Lk8j44Cp3RlJfxtXGq2GroWhKhnU6MhOk5Whi7iSI9izapX7IQ/CSai83agxOBqJ7zvUa
          Ann4zVyOi0gS/GeIDOuj1AMP+eH1LVHJiMWTE+z4pVxDbeflxMvPfu3SrZ8BgfJ7JfNOe
          JXOZsKTsvwoWEvPDcvcymtHJAKnhm9FhWsk951gDNiK6UEWheWdwF4Uhmw4dd7IVqkF3w
          BrkAYczq/6YTOXAldPhZaIptBjwyAr8ql9AG2tR6iJUPWYEWfBUgJ8T5m8Hfnu9ebSOLj
          eJMYssPvPhu6OL8NolscRZPIh1+LRySiNYlJ4/dwAzsfZizhWT5cfqQYaXvF1VPcWizSG
          +ohikS8VS/AspgfTXA5RJVAwc2ahBx5yGdTejTBKiYwxj8ZZPxUZWBdeDJa//i2tMConv
          2rCDw/HBT8tHF80qz9/RDXfAVcp2koqGOAV3+NAaExKWEmmzs6jzMShf4Re2cweCxRBHS
          KPqZAkRDJp7WAHoDlDSiQ0hdGBHTkXl2Jkn1GLUF/uLOhL8R9DKuyit0gTWUdhpETePgN
          IM509LmSiIKaz0raKtllobSXInXVIjDAq8DSUSpXKo5xYe2EnjtaFNF4BKANX/FYPm5ti
          C2TflJcjFVENdGQYjscduPZ+MQH8ozL61H7wISzEJKzIC9kSwtRhGfXocINMsE=
