#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: vault-psp-rolebinding
  labels:
    chart_group: vault
spec:
  releaseName: sva-vault-psp-rolebinding
  chart:
    spec:
      chart: psp-rolebinding
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: vault-psp-rolebinding-static-overrides
      valuesKey: vault-psp-rolebinding-static-overrides.yaml
    - kind: Secret
      name: vault-psp-rolebinding-system-overrides
      valuesKey: vault-psp-rolebinding-system-overrides.yaml
