#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
PKG_DIR="vault-helm"
STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/vault-armada-app/${PKG_DIR}/${PKG_DIR})

mkdir -p ${PKG_BUILD_ROOT}
pushd ${PKG_BUILD_ROOT}

# Local mirror workaround until CGCS_BASE mirror is supported.
STX_MIRROR=$(realpath "/import/mirrors/starlingx")

# Download vault helm chart source package.
VAULT_PKG="helm-charts-vault-0-6-0.tar.gz"
VAULT_SRC_PATH=$(realpath ${STX_MIRROR}/downloads/${VAULT_PKG})
cp ${VAULT_SRC_PATH} ${PKG_BUILD_ROOT}

# Extract the vault helm chart tar file.
tar xfzvv ${VAULT_PKG}

# Copy source files to the build directory.
cp -pr ${SRC}/files/* ${SRC}/helm-charts/* ${PKG_BUILD_ROOT}
