#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: vault
  labels:
    chart_group: vault
spec:
  releaseName: sva-vault
  chart:
    spec:
      chart: vault
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: vault-static-overrides
      valuesKey: vault-static-overrides.yaml
    - kind: Secret
      name: vault-system-overrides
      valuesKey: vault-system-overrides.yaml
