{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $cn := printf "fluentd.%s.svc.cluster.local" .Release.Namespace }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}
{{ $client := genSignedCert "" nil nil 365 $ca }}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "vault.name" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ template "vault.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  tls.crt: {{ b64enc $ca.Cert }}
  tls.key: {{ b64enc $ca.Key }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  creationTimestamp: null
  name: ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ template "vault.name" . }}-ca
status: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  creationTimestamp: null
  name: vault-server-tls
  namespace: {{ .Release.Namespace }}
spec:
  # Secret names are always required.
  secretName: vault-server-tls
  duration: 2160h0m0s  # 90d
  renewBefore: 360h0m0s  # 15d
  usages:
  - server auth
  - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - sva-{{ template "vault.name" . }}
  - '*.sva-{{ template "vault.name" . }}-internal'
  - '*.{{ .Release.Namespace }}.pod.cluster.local'
  - sva-{{ template "vault.name" . }}.{{ .Release.Namespace }}
  - sva-{{ template "vault.name" . }}.{{ .Release.Namespace }}.svc
  - sva-{{ template "vault.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  - sva-{{ template "vault.name" .}}-active.{{ .Release.Namespace }}.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - stx
status: {}
