#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: vault-manager
  labels:
    chart_group: vault
spec:
  releaseName: sva-vault-manager
  chart:
    spec:
      chart: vault-manager
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: vault-manager-static-overrides
      valuesKey: vault-manager-static-overrides.yaml
    - kind: Secret
      name: vault-manager-system-overrides
      valuesKey: vault-manager-system-overrides.yaml
