#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: vault
resources:
  - helmrelease.yaml
secretGenerator:
  - name: vault-manager-static-overrides
    files:
      - vault-manager-static-overrides.yaml
  - name: vault-manager-system-overrides
    files:
      - vault-manager-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
