#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
PKG_DIR="stx-vault-helm"

STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/vault-armada-app/${PKG_DIR}/${PKG_DIR})
PSP_HELM_CHARTS=$(realpath ${STX_BASE}/helm-charts/psp-rolebinding/psp-rolebinding/helm-charts)

mkdir -p ${PKG_BUILD_ROOT}

# Copy PSP rolebinding helm charts to the build directory.
cp -pr ${PSP_HELM_CHARTS} ${PKG_BUILD_ROOT}

# Copy source files.
cp -pr ${SRC}/files ${PKG_BUILD_ROOT}
cp -pr ${SRC}/helm-charts/Makefile ${PKG_BUILD_ROOT}/helm-charts
cp -pr ${SRC}/manifests ${PKG_BUILD_ROOT}
